# ------------------------------------------------------------------------------------
# Renames exported Gradescope submissions (in place).

# README:
# You need to cd into the correct folder with the .yaml file and the submissions.
# You need to change the 'dst' variable in the code to the file nameming convention you want.
# You will need to change the 'export_folder_name' to the path of the folder containing the 
# submissions to rename that should also contain the .yaml file generated by Gradescope. 
# Remember to add an escape to the folder path "C:\\Folder\\Path"
# ------------------------------------------------------------------------------------

import os
import sys
import yaml

# setting variables
export_folder_name = "C:\\Users\\Dell\\Downloads\\GA Test 2"

# open .yaml metadata file
metadata = export_folder_name + "\\submission_metadata.yml"
with open(metadata, 'r') as stream:
    submission_metadata = yaml.safe_load(stream)

i = 0
dir_list = os.listdir(export_folder_name)
num_of_files = len(dir_list) - 1

for filename in dir_list:
    if filename != 'submission_metadata.yml':
        submitters = submission_metadata[filename][':submitters']
        names = map(lambda submitter: submitter[':name'], submitters)
        sids = map(lambda submitter: submitter[':sid'], submitters)
        joined_sids = "".join("_".join(sids))
        joined_names = "_".join("_".join(names).split(" "))
        joined_names = joined_names[joined_names.find("_")+1:] + "_" + joined_names[:joined_names.find("_")] 

        src = export_folder_name + '/' + filename
        dst = export_folder_name + '/' + 'EEE3096S_GA Test 2' + "_" + joined_sids.upper() + "_" + "2022" + '.pdf'
        os.rename(src, dst)
        i += 1
        print('Renamed ' + str(i) + ' of ' + str(num_of_files))

print("Done!")
